name: End GitHub Actions job with gha-trigger
description: End GitHub Actions job with gha-trigger
inputs:
  state:
    description: job status
    required: false

  github_token:
    description: GitHub Access Token to update a commit status
    required: true
  update_commit_status:
    description: Update a commit status
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: gha-trigger/commit-status-action@feat/support-workflow
      with:
        github_token: ${{inputs.github_token}}
        state: ${{inputs.state}}
        update_commit_status: ${{inputs.update_commit_status}}
        needs: ${{inputs.needs}}
