name: End GitHub Actions job with gha-trigger
description: End GitHub Actions job with gha-trigger
inputs:
  state:
    description: job status
    required: false

  github_token:
    description: GitHub Access Token to update a commit status
    required: true
  needs:
    description: needs context.
    required: false
runs:
  using: composite
  steps:
    - uses: gha-trigger/commit-status-action@v0.1.0
      with:
        github_token: ${{inputs.github_token}}
        state: ${{inputs.state}}
        needs: ${{inputs.needs}}
